package day10;

public class Exception1 {

public static void main(String[] args) {
	
		try
		{
			int a = 10;
			int b =0;
			System.out.println(a/b);
			
			System.out.println("the num");
		}
		catch(Exception obj)
		{
			
				System.out.println("continue without stopping");
		}
	}
}		


